#John Veillette

import argparse
import sys
import csv
import tree
import treemap

def draw(filename, output_filename = None):
	'''
	Draws a treemap student flow represented in the specified .csv filename.

	Inputs:
		filename: a .csv file as generated by student-transfer-reports.py 
		output_filename: a .png filename to store the image of the treemap;
						(will cause error if non .png filename is specified)
	'''
	t = load_from_file(filename)
	treemap.draw_treemap(t, output_filename = output_filename)

def load_from_file(filename):
	'''
	Input: a .csv file

	Returns: a TreeNode object

	'''
	t = tree.TreeNode('', '', 0)
	children = t.get_children_as_dict()
	with open(filename) as f:
		reader = csv.reader(f, skipinitialspace=True)
		header = next(reader)
		for row in reader:
			school = dict(zip(header, row))
			name = school['School Name']
			count = school['Count']
			weight = t.weight + int(count)
			t.weight = weight
			label = "%s (%s)" % (name, weight)
			children[name] = tree.TreeNode('', label, int(count))
	return t
